### ISSUE TITLE
httpapi.py points on wrong urls.py location

### ISSUE THREAD

**Issue by goneri** [ansible-community/collection_migration#448]
```
The full traceback is:
Traceback (most recent call last):
  File "/home/goneri/git_repos/ansible-collections/vmware_rest/.virtualenv/py37/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/home/goneri/git_repos/ansible-collections/vmware_rest/.virtualenv/py37/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 601, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/home/goneri/git_repos/ansible-collections/vmware_rest/.virtualenv/py37/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 895, in _get_connection
    ansible_playbook_pid=to_text(os.getppid())
  File "/home/goneri/git_repos/ansible-collections/vmware_rest/.virtualenv/py37/lib/python3.7/site-packages/ansible/plugins/loader.py", line 557, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/home/goneri/git_repos/ansible-collections/vmware_rest/.virtualenv/py37/lib/python3.7/site-packages/ansible/plugins/loader.py", line 530, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/goneri/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/httpapi.py", line 171, in <module>
    from ansible_collections.community.general.plugins.module_utils.urls import open_url
ModuleNotFoundError: No module named 'ansible_collections.community.general.plugins.module_utils.urls'
fatal: [vcenter.test]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

At
~/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/httpapi.py +171, I've got:

`from ansible_collections.community.general.plugins.module_utils.urls import open_url`

But the file does not actually exist. `urls.py` is in core.

**Comment by bcoca** [comment]
When i run migration i get
```from ansible.module_utils.urls import open_url```

which is correct

**Comment by bcoca** [comment]
so updated migrate.py and i can now reproduce b2e728cd099b96596957c76e33b7f84b00e46ad3

**Comment by mkrizek** [comment]
So this is actually caused by https://github.com/ansible-community/collection_migration/commit/063c2fc396be42528338ce1ce5b7fa3627a2f48b#diff-9436d08f8a9a7146dda153bc5f0c8943R533.
